on: pull_request

name: Foundry Tests

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.0.6
        with:
          version: nightly-5ac78a9cd4b94dc53d1fe5e0f42372b28b5a7559

      - name: Run format
        run: forge fmt --check

      - name: Install Tenderly CLI
        run: curl https://raw.githubusercontent.com/Tenderly/tenderly-cli/master/scripts/install-linux.sh | sudo sh

      - name: Run tests
        run: |
          export RPC_URL=$(tenderly devnet spawn-rpc --project arcadia-finance-tenderly --template basetest --account ${TENDERLY_ACCOUNT_ID} --access_key ${TENDERLY_ACCESS_KEY} 2>&1)
          FOUNDRY_PROFILE=gh forge test -vvv
        env:
          TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
          TENDERLY_ACCOUNT_ID: ${{ secrets.TENDERLY_ACCOUNT_ID }}

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
